apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndoejs
spec:
  selector:
    matchLabels:
      run: nodejs
  replicas: 1
  template:
    metadata:
      labels:
        run: nodejs
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: nodejs
        image: docker.io/sanwukong/nodejs:lts
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
