apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      run: nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx
        name: nginx
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: nginx
        image: docker.io/sanwukong/nginx
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: service-nginx
spec:
  selector:
    run: nginx
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30949
  
